# Usa l'immagine base di Node.js
FROM node:20-alpine

# Imposta la directory di lavoro all'interno del container
WORKDIR /home/src/webapp

# Installa le dipendenze globali necessarie (come create-react-app se necessario)
RUN npm install -g create-react-app

# Espone la porta su cui gira l'applicazione React
EXPOSE 3000

# RUN cd src/webapp

# Comando predefinito (puoi cambiarlo o commentarlo se preferisci usare npm start)
CMD ["npm", "run", "dev"]


# CREATE IMAGE
# docker build -t frontend_react_dev_fastapi .

# CREATE INSTANCE
# docker run -it --name frontend_dev_fastapi -p 3000:3000 -v "C:\Users\polin\OneDrive - Devnut\Documenti\Progetti\4.Tutorials\3.React\React_FastAPI\frontend\src":/home/src frontend_react_dev_fastapi
