managers:
  Alberto:
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  Antonio:
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  Simone:
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  Danilo:
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  Orazio:
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  Vigani:
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  Lorenzo:
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  Robi:
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  Manu:
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  Cris:
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []