managers:
  1:
    teamName: Alberto
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  2:
    teamName: Antonio
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  3:
    teamName: Simone
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  4:
    teamName: Danilo
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  5:
    teamName: Orazio
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  6:
    teamName: Vigani
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  7:
    teamName: Lorenzo
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  8:
    teamName: Robi
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  9:
    teamName: Manu
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []
  10:
    teamName: Cris
    Crediti: 500
    Slot_Rimanenti: 25
    MassimoRilancio: 476
    Rosa:
      Portieri: []
      Difensori: []
      Centrocampisti: []
      Attaccanti: []