columns:
  season_: "Season"
  team_: "Team"
  player_: "Player"
  nation_: "Nationality"
  pos_: "Role"
  age_: "Age"
  Playing_Time_MP: "Presences"
  Performance_Gls: "Gol"
  Performance_Ast: "Assist"
  Performance_G-PK: "Penalty Goal"
  Performance_PK: "Penalty Attempt"
  Expected_xG: "Expected Goals"
  Expected_xAG: "Expected Assists"
  Progression_PrgC: "Progressive Carries"
  Progression_PrgP: "Progressive Passes"
  Progression_PrgR: "Progressive Receptions"
  Per_90_Minutes_Gls: "Goals per 90 minutes"
  Per_90_Minutes_Ast: "Assists per 90 minutes"
  Per_90_Minutes_xG: "Expected Goals per 90 minutes"
  Per_90_Minutes_xAG: "Expected Assists per 90 minutes"